import { RESPONSE_TYPE, type ResponseType } from './response-type';

export const RESPONSE_CODE = {
    // --- auth success ---
    MAGIC_LINK_SENT: 'MAGIC_LINK_SENT',
    LOGGED_OUT: 'LOGGED_OUT',
    PASSWORD_SET: 'PASSWORD_SET',
    PASSWORD_DELETED: 'PASSWORD_DELETED',
    ACCOUNT_DELETED: 'ACCOUNT_DELETED',
    ACCOUNT_RESTORED: 'ACCOUNT_RESTORED',

    // --- users success ---
    LANG_UPDATED: 'LANG_UPDATED',

    // --- payments error ---
    ALREADY_SUBSCRIBED: 'ALREADY_SUBSCRIBED',
    SUBSCRIPTION_REQUIRED: 'SUBSCRIPTION_REQUIRED',
    NO_BILLING_ACCOUNT: 'NO_BILLING_ACCOUNT',
    PAYMENT_TYPE_DISABLED: 'PAYMENT_TYPE_DISABLED',

    // --- errors ---
    UNAUTHORIZED: 'UNAUTHORIZED',
    VALIDATION_ERROR: 'VALIDATION_ERROR',
    NOT_FOUND: 'NOT_FOUND',
    RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
    INSUFFICIENT_CREDITS: 'INSUFFICIENT_CREDITS',
    INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type ResponseCode =
    (typeof RESPONSE_CODE)[keyof typeof RESPONSE_CODE];

/** Маппінг код → тип для фронту (колір нотифікації тощо) */
export const RESPONSE_CODE_TYPE: Record<ResponseCode, ResponseType> = {
    [RESPONSE_CODE.MAGIC_LINK_SENT]: RESPONSE_TYPE.SUCCESS,
    [RESPONSE_CODE.LOGGED_OUT]: RESPONSE_TYPE.SUCCESS,
    [RESPONSE_CODE.PASSWORD_SET]: RESPONSE_TYPE.SUCCESS,
    [RESPONSE_CODE.PASSWORD_DELETED]: RESPONSE_TYPE.SUCCESS,
    [RESPONSE_CODE.LANG_UPDATED]: RESPONSE_TYPE.SUCCESS,
    [RESPONSE_CODE.ACCOUNT_DELETED]: RESPONSE_TYPE.SUCCESS,
    [RESPONSE_CODE.ACCOUNT_RESTORED]: RESPONSE_TYPE.SUCCESS,
    [RESPONSE_CODE.ALREADY_SUBSCRIBED]: RESPONSE_TYPE.ERROR,
    [RESPONSE_CODE.SUBSCRIPTION_REQUIRED]: RESPONSE_TYPE.ERROR,
    [RESPONSE_CODE.NO_BILLING_ACCOUNT]: RESPONSE_TYPE.ERROR,
    [RESPONSE_CODE.PAYMENT_TYPE_DISABLED]: RESPONSE_TYPE.ERROR,
    [RESPONSE_CODE.UNAUTHORIZED]: RESPONSE_TYPE.ERROR,
    [RESPONSE_CODE.VALIDATION_ERROR]: RESPONSE_TYPE.ERROR,
    [RESPONSE_CODE.NOT_FOUND]: RESPONSE_TYPE.ERROR,
    [RESPONSE_CODE.RATE_LIMIT_EXCEEDED]: RESPONSE_TYPE.ERROR,
    [RESPONSE_CODE.INSUFFICIENT_CREDITS]: RESPONSE_TYPE.ERROR,
    [RESPONSE_CODE.INTERNAL_ERROR]: RESPONSE_TYPE.ERROR,
};
